INF272 Deliverable 2/INF272 Deliverable 2/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace INF272_Deliverable_2.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult AdminHome()
        {
            return View();
        }
    }
}

INF272 Deliverable 2/INF272 Deliverable 2/Controllers/FreelancerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace INF272_Deliverable_2.Controllers
{
    public class FreelancerController : Controller
    {
        // GET: Freelancer
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Report()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult User_Profile()
        {
            return View();
        }
    }
}

INF272 Deliverable 2/INF272 Deliverable 2/Controllers/UserRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace INF272_Deliverable_2.Controllers
{
    public class UserRegistrationController : Controller
    {
        // GET: UserRegistration
        public ActionResult UserRegistration()
        {
            return View();
        }
        public ActionResult FreelancerRegistration()
        {
            return View();
        }
        public ActionResult EmployerReg()
        {
            return View();
        }
    }
}

INF272 Deliverable 2/INF272 Deliverable 2/Views/Admin/AdminHome.cshtml

<div class="container" style="background-color:lightgray">
    <div class="row">
        <div class="col-md-5">
            <div style="float:right;margin-top:5rem;margin-right:20rem;">
                <h3> Admin</h3>

            </div>
            <i class="glyphicon glyphicon-user" style="font-size:100px; margin-top:3rem;"></i>
        </div>


        <div class="text-center col-md-2" style="margin-top:8rem;">


        </div>

        <div class="col-md-5">
            <div>
                <img style="width:45%; height:45%;float:right;" src="~/Pictures/logo_transparent.png" />

            </div>
        </div>
        <div class="col-md-5">
            <h4 style="color:purple;"> Current Accounts </h4>
        </div>
        <div class="input-group col-md-5" style="float:right">
            <input type="text" class="form-control" placeholder="Search for an account">
            <div class="input-group-append">
                <button class="btn btn-secondary" type="button">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
            </div>
        </div>
    </div>

    <div class="container" style="padding-bottom:2rem">
        <table id="table" class="table  table-hover table-responsive"
               style="margin-left: auto;">
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Catergories</th>
                <th>Date Created</th>
                <th>Rating</th>
                <th></th>
                <th></th>
            </tr>


            <tr>
                <td>Mike</td>
                <td>Active</td>
                <td>Plumbing</td>
                <td>01/02/2020 </td>
                <td>4</td>
                <td><button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#exampleModalCenter">Disable</button></td>
                <td><button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#delete">Delete</button></td>
            </tr>
            <tr>
                <td>Rob</td>
                <td>Active</td>
                <td>Photography</td>
                <td>05/04/2020 </td>
                <td>5</td>
                <td><button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#exampleModalCenter">Disable</button></td>
                <td><button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#delete">Delete</button></td>
            </tr>
            <tr>
                <td>Dhiren</td>
                <td>Active</td>
                <td>Plumbing</td>
                <td>09/08/2020 </td>
                <td>4</td>
                <td><button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#exampleModalCenter">Disable</button></td>
                <td><button type="button" class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#delete">Delete</button></td>
            </tr>

        </table>

    </div>
    <div style="padding-bottom:9rem">
        <div style="float:right;">
            <button class="btn btn-primary btn-sm " onclick="location.href='@Url.Action("UserProfile", "FreeLancer")'">Edit Categories</button>
            <br />
            <div style="padding-top:1rem">
                <button class="btn btn-primary btn-sm ">Print Report</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Disable Account</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body center-block text-center text-info">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <label class="input-group-text" for="inputGroupSelect01">Reason for disabling</label>
                    </div>
                    <select class="custom-select" id="inputGroupSelect01">
                        <option selected>Choose...</option>
                        <option value="1">Violent Content</option>
                        <option value="2">Harmful Acts</option>
                        <option value="3">Spam</option>
                        <option value="4">Offensive Pictures</option>
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Confirm</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="deleteCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteLongTitle">Delete Account</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Confirm deleting of the account
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Confirm</button>
            </div>
        </div>
    </div>
</div>


INF272 Deliverable 2/INF272 Deliverable 2/Views/Freelancer/Create.cshtml
    <div class="row">
        <div class="col-md-4">
            <img style="width:70%; height:70%;" src="~/Pictures/Logo.jpeg" />
        </div>
        


        <div class="text-center col-md-4" style="margin-top:5rem;">
            <h2> You are now registered</h2>
        </div>

        <div class="col-md-4">

        </div>

    </div>


<div class="row" style="padding-bottom:40px;">

    <div style="float: left; width: 50%; ">
        <div style="margin-left:17%">
            <label for="#Desc">Enter a description of your work:</label>
            <textarea type="text" class="form-control" id="Desc"
                      placeholder="Enter text here" rows="10" cols="50" maxlength="100"
                      style="width: 80%; height:90%; max-width: 100%;resize: none; border-radius: 10px;"></textarea>
        </div>
    </div>

    <div style="float: right; width: 50%;">
        <div style="margin-left:15%">
            <label for="#Photo">Upload photos of your work</label>  <span><i class="glyphicon glyphicon-folder-open"></i></span>
            <textarea type="text" class="form-control" id="Photo"
                      placeholder="Photos will be displayed here:" rows="10" cols="50" maxlength="100"
                      style="width: 80%; height: 90%; max-width: 100%; resize: none; border-radius: 10px;"></textarea>
        </div>
    </div>

</div>
<div style="padding-bottom:4%;margin-left:93rem">
    <button class="btn btn-primary" onclick="window.location.href='@Url.Action("User_Profile", "Freelancer")'">Upload Portfolio</button>
</div>

INF272 Deliverable 2/INF272 Deliverable 2/Views/Freelancer/Edit.cshtml
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <div style="float:right;margin-top:5rem;margin-right:20rem;">
                <h4> Yahil Rathod</h4>
                <h5>Plumber</h5>
                <h5>Laudium, Gauteng</h5>
            </div>
            <i class="glyphicon glyphicon-user" style="font-size:100px; margin-top:3rem;"></i>
        </div>


        <div class="text-center col-md-2" style="margin-top:4rem">
            <h1>Update Portfolio</h1>

        </div>

        <div class="col-md-5">
            <div style="margin-bottom:90px">
                <img style="width:60%; height:60%;float:right;" src="~/Pictures/Logo.jpeg" />
            </div>
           
        </div>

    </div>

    <div class="row" style="padding-bottom:40px;">

        <div style="float: left; width: 50%; ">
            <div style="margin-left:10rem">
                <label for="#Desc">Enter a description of your work:</label>
                <textarea type="text" class="form-control" id="Desc"
                          placeholder="Enter text here" rows="10" cols="50" maxlength="100"
                          style="width: 80%; height:90%; max-width: 100%;resize: none; border-radius: 10px;"></textarea>
            </div>
        </div>

        <div style="float: right; width: 50%;">
            <div style="margin-left:10rem">
                <label for="#Photo">Upload photos of your work</label>  <span><i class="glyphicon glyphicon-folder-open"></i></span>
                <textarea type="text" class="form-control" id="Photo"
                          placeholder="Photos will be displayed here:" rows="10" cols="50" maxlength="100"
                          style="width: 80%; height: 90%; max-width: 100%; resize: none; border-radius: 10px;"></textarea>
            </div>
        </div>

    </div>

    <div style="padding-bottom:4%;margin-left:82rem">
        <button style="width:110px" class="btn btn-primary btn-"onclick="window.location.href='@Url.Action("User_Profile", "Freelancer")'">Go Back</button>
        <button class="btn btn-primary"onclick="window.location.href='@Url.Action("User_Profile", "Freelancer")'">Save my details</button>
    </div>
</div>

INF272 Deliverable 2/INF272 Deliverable 2/Views/Freelancer/Report.cshtml
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <div style="float:right;margin-top:5rem;margin-right:20rem;">
                <h4> Yahil Rathod</h4>
                <h5>Plumber</h5>
                <h5>Laudium, Gauteng</h5>
            </div>
            <i class="glyphicon glyphicon-user" style="font-size:100px; margin-top:3rem;"></i>
        </div>


        <div class="text-center col-md-2" style="margin-top:8rem;">


        </div>

        <div class="col-md-5">
            <div style="margin-bottom:90px">
                <img style="width:60%; height:60%;float:right;"src="~/Pictures/Logo.jpeg" />
            </div>
            
        </div>

    </div>

    <div class="container" style="padding-bottom:2rem">
        <label for="table ">Who has gotten in touch with you</label>
        <table id="table" class="table  table-hover table-responsive"
               style="margin-left: auto; margin-right: auto;">
            <tr>
                <th>Name</th>
                <th>Business Name</th>
                <th>Email</th>
                <th>Date</th>
            </tr>


            <tr>
                <td>Mike</td>
                <td>N/A</td>
                <td>Mike@gmail.com </td>
                <td>01/02/2020 </td>
            </tr>
            <tr>
                <td>Jane</td>
                <td>Sasol</td>
                <td>jane@mweb.co.za </td>
                <td>06/03/2020 </td>
            </tr>
            <tr>
                <td>Nemo</td>
                <td>EY</td>
                <td>Nemo@mweb.co.za</td>
                <td>02/04/2020 </td>
            </tr>

        </table>

    </div>
    <div style="padding-bottom:9rem">
        <div style="float:right;">
            <button style="width:100px" class="btn btn-primary "onclick="window.location.href='@Url.Action("User_Profile", "Freelancer")'">Go Back</button>
            <br />
            <div style="padding-top:1rem">
                <button class="btn btn-primary ">Print Report</button>
            </div>
        </div>
    </div>
</div>

INF272 Deliverable 2/INF272 Deliverable 2/Views/Freelancer/User_Profile.cshtml
<style>

    img {
        margin: 5px;
    }
</style>

<span style="margin-left:96%;font-size:20px" class="glyphicon glyphicon-lock"></span>

<div class="row" style="padding-bottom:50px">
    <div class="col-md-5">
        <div style="float:right;margin-top:4rem;margin-right:20rem;">
            <h4> Yahil Rathod</h4>
            <h5>Plumber</h5>
            <h5>Laudium, Gauteng</h5>
        </div>
        <i class="glyphicon glyphicon-user" style="font-size:100px; margin-top:2rem;"></i>
    </div>


    <div class="text-center col-md-2" style="margin-top:2rem">

        <h1>Welcome <br /> <span style="font-size:21px"> this is your profile</span></h1>

    </div>

    <div class="col-md-5">
        <div>
            <img style="width:50%; height:50%;margin-left:58%; " src="~/Pictures/Logo.jpeg" />
        </div>
        
    </div>

</div>

<div class="row">

    <div class="col-md-6">
        <p style="width:40rem;">
            Hi My name is Yahil Rathod and i am an experienced plumber.
            I trained at the technical college in Pretoria namely: Tuks Plumbing college.
            I was Top of my class and was able to fix any blocked toilet or dripping pipe.
            I have always prided myself with my exceptional quality contorl and affordability.
            I am available 24/7 for any emergancy and willing to travel vast distances in order to fulfiil
            my duties and oath I undertook at college. I spezialize in pipes and water systems and my favorite jobs
            include clearing out blocked drains and fixing leaks. Make sure to make a booking in advance as i am booked out.
            Call the best flush the rest.
        </p>
    </div>


    <div class="col-md-6">

        <div class="d-flex flex-row">
            <div class="col-md-4">
                <img style="width:150px;height:100px;" class="img-fluid" src="~/Pictures/Freelancer/plumber1.jpg" />

            </div>
            <div class="col-md-4">
                <img style="width:150px;height:100px;" class="img-fluid" src="~/Pictures/Freelancer/plumber2.jpg" />

            </div>
            
            <div class="col-md-4">
                <img style="width:150px;height:100px;" class="img-fluid" src="~/Pictures/Freelancer/plumber3.jpg"  />
             
            </div>

        </div>
        <div class="d-flex flex-row">
            <div class="col-md-4">
                <img style="width:150px;height:100px;" class="img-fluid" src="~/Pictures/Freelancer/plumber4.jpg" />
                
            </div>
            <div class="col-md-4">
                <img style="width:150px;height:100px;" class="img-fluid" src="~/Pictures/Freelancer/plumber5.jpg"  />
                
            </div>
            <div class="col-md-4">
                <img style="width:150px;height:100px;" class="img-fluid" src="~/Pictures/Freelancer/plumber6.jpg"  />
                
            </div>

        </div>
    </div>

</div>
<div style="padding-bottom:4%;margin-left:92rem;margin-top:4rem;">
    <button style="width:110px" class="btn btn-primary btn-" onclick="window.location.href='@Url.Action("Edit", "Freelancer")'">Edit Profile</button>
    <button class="btn btn-primary" style="width:100px" onclick="window.location.href='@Url.Action("Report", "Freelancer")'">Report</button>
</div>

INF272 Deliverable 2/INF272 Deliverable 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

INF272 Deliverable 2/INF272 Deliverable 2/Views/UserRegistration/EmployerReg.cshtml

@{
    ViewBag.Title = "UserRegistration";
}
<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script>
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#ImageId')
                            .attr('src', e.target.result);
                    };

                    reader.readAsDataURL(input.files[0]);
                }
            }
    </script>
</head>
<form class="form-horizontal">
    <fieldset>
        <div id="legend">
            <div class="row">
                <div class="col-md-4">
                    <img style="width:70%; height:70%;" src="~/Pictures/Logo.jpeg" />
                  
                </div>
                <div class="col-md-6">
                    <h2 style="height:70%">Employer Registration</h2>
                    <br />
                    <h4>Please Complete the form</h4>
                </div>
            </div>
            <hr />
            <div class="col-md-6">
                <div class="form-group">
                    <label for="UserName"><b>Business Name</b></label>
                    <div class="controls">
                        <input type="text" placeholder="Enter Business Name" name="BName" id="BName">
                    </div>
                </div>

                <div class="control-group">
                    <label for="Name"><b>Name:</b></label>
                    <div class="controls">
                        <input type="text" placeholder="Enter Name" name="Name" id="Name" required>
                    </div>
                </div>

                <div class="control-group">
                    <label for="SurName"><b>Surname:</b></label>
                    <div class="controls">
                        <input type="text" placeholder="Enter Surname" name="Surname" id="Surname" required>
                    </div>
                </div>

                <div class="control-group">
                    <label for="EmailAddress"><b>Email Address:</b></label>
                    <div class="controls">
                        <input type="text" placeholder="Enter E-mail" name="Email" id="Email" required>
                    </div>
                </div>
                <div class="control-group">
                    <label for="Province"> <b>Province: </b></label>
                    <div class="controls">
                        <select name="SProvince" id="SProvince">
                            <option value="Gauteng">Gauteng</option>
                            <option value="Limpopo">Limpopo</option>
                            <option value="Free State">Free State</option>
                            <option value="Eastern Cape">Eastern Cape</option>
                            <option value="Western Cape">Western Cape</option>
                            <option value="Kwazulu- Natal">Kwazulu-Natal</option>
                            <option value="North West">North West</option>
                            <option value="Northern Cape">Northern Cape</option>
                            <option value="Mpumalanga">Mpumalanga</option>
                        </select>
                    </div>
                </div>

                <div class="control-group">
                    <label for="City"> <b> City:</</b></label>
                    <div class="controls">
                        <select name="SCity" id="SCity">
                            <option value="Johannesburg">Johannesburg</option>
                            <option value="Pretoria">Pretoria</option>
                            <option value="Durban">Durban</option>
                            <option value="Bloemfontien">Bloemfontien</option>
                            <option value="Cape Town">Cape Town</option>
                            <option value="Port Elizabeth">Port Elizabeth</option>
                            <option value="Polokwane">Polokwane</option>
                            <option value="East London">East London</option>
                            <option value="Stellenbosch">Stellenbosch</option>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label for="Subhurb"><b>Subhurb:</b></label>
                    <div class="controls">
                        <input type="text" placeholder="Enter Subhurb" name="Subhurb" id="Subhurb" required>
                    </div>
                </div>

            </div>
            <div class="col-md-6">
                <div class="control-group">
                    <label for="Image"> <b> Image:</b></label>
                    <div class="controls">
                        <input type="file" name="myImage" accept="image/*" onchange="readURL(this);" />
                        <br />
                        <img id="ImageId" style="height:400px; width:800px; object-fit:fill; " />
                    </div>
                </div>
                <hr>
                <div class="btn-group" role="group" aria-label="Basic example" style="float:right">
                    <button type="submit" class="btn btn-secondary">&laquo;Back</button>
                    <button type="submit" class="btn btn-secondary">Register</button>
                </div>
            </div>
        </div>
    </fieldset>
</form>

INF272 Deliverable 2/INF272 Deliverable 2/Views/UserRegistration/FreelancerRegistration.cshtml

@{
    ViewBag.Title = "UserRegistration";
}

<head>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#ImageId')
                        .attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
</head>
<style>
</style>
<form class="form-horizontal">
    <fieldset>
        <div id="legend">
            <div class="row">
                <div class="col-md-4">
                    <img style="width:70%; height:70%;" src="~/Pictures/Logo.jpeg" />
                </div>
                <div class="col-md-6">
                    <h2 style="height:70%">Freelancer Registration</h2>
                    <br />
                    <h4>Please Complete the form</h4>
                </div>
            </div>
            <hr />
            <div class="col-md-6">
                <label for="Bcategory"><b>Business Category</b></label>
                <div class="controls">
                    <select name="BCateogory" id="BCategory">
                        <option value="OPlumber">Plumber</option>
                        <option value="OPhotographer">Photographer</option>
                        <option value="OLandscaping">Landscaping</option>
                        <option value="OPainting">Painting</option>
                        <option value="OElectrician">Electrician</option>
                        <option value="OCarpenter">Carpenter</option>
                    </select>
                </div>
                <div class="control-group">
                    <label for="UserName"><b>Business Name</b></label>
                    <div class="controls">
                        <input type="text" placeholder="Enter Business Name" name="BName" id="BName">
                    </div>
                </div>
                <div class="control-group">
                    <label for="Name"><b>Name:</b></label>
                    <div class="controls">
                        <input type="text" placeholder="Enter Name" name="Name" id="Name" required>
                    </div>
                </div>
                <div class="control-group">
                    <label for="SurName"><b>Surname:</b></label>
                    <div class="controls">
                        <input type="text" placeholder="Enter Surname" name="Surname" id="Surname" required>
                    </div>
                </div>
                <div class="control-group">
                    <label for="EmailAddress"><b>Email Address:</b></label>
                    <div class="controls">
                        <input type="text" placeholder="Enter E-mail" name="Email" id="Email" required>
                    </div>
                </div>
                <div class="control-group">
                    <label for="Province"> <b>Province: </b></label>
                    <div class="controls">
                        <select name="SProvince" id="SProvince">
                            <option value="Gauteng">Gauteng</option>
                            <option value="Limpopo">Limpopo</option>
                            <option value="Free State">Free State</option>
                            <option value="Eastern Cape">Eastern Cape</option>
                            <option value="Western Cape">Western Cape</option>
                            <option value="Kwazulu- Natal">Kwazulu-Natal</option>
                            <option value="North West">North West</option>
                            <option value="Northern Cape">Northern Cape</option>
                            <option value="Mpumalanga">Mpumalanga</option>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label for="City"> <b> City:</</b></label>
                    <div class="controls">
                        <select name="SCity" id="SCity">
                            <option value="Johannesburg">Johannesburg</option>
                            <option value="Pretoria">Pretoria</option>
                            <option value="Durban">Durban</option>
                            <option value="Bloemfontien">Bloemfontien</option>
                            <option value="Cape Town">Cape Town</option>
                            <option value="Port Elizabeth">Port Elizabeth</option>
                            <option value="Polokwane">Polokwane</option>
                            <option value="East London">East London</option>
                            <option value="Stellenbosch">Stellenbosch</option>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label for="Subhurb"><b>Subhurb:</b></label>
                    <div class="controls">
                        <input type="text" placeholder="Enter Subhurb" name="Subhurb" id="Subhurb" required>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="control-group">

                <label for="Image"> <b> Image:</b></label>
                <div class="controls">
                    <input type="file" name="myImage" accept="image/*" onchange="readURL(this);" />
                    <br />
                    <img id="ImageId" style="height:400px; width:800px; object-fit:fill; " />
                </div>
            </div>
            <div class="btn-group" role="group" aria-label="Basic example" style="float:right">
                <button type="submit" class="btn btn-secondary">&laquo;Back</button>
                <button type="submit" class="btn btn-secondary">Register</button>
            </div>
        </div>

    </fieldset>

</form>





